language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then export _authToken=$NPM_TOKEN; fi
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
