sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - 7
  - 6
  - 5
  - 4
  - '0.10'
before_script:
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
