language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "iojs-v1.7.1"
  - "iojs-v1.6.4"
  - "iojs-v1.5.1"
before_install:
  - npm install -g npm
before_script:
  - npm install
notifications:
  email: false
